.de d \" begin display
.sp
.in +4
.nf
..
.de e \" end display
.in -4
.fi
.sp
..
.TH "HXSELECT" "1" "10 Jul 2011" "7.x" "HTML-XML-utils"
.SH NAME
hxselect \- extract elements that match a (CSS) selector
.SH SYNOPSIS
.B hxselect
.RB "[\| " \-i " \|]"
.RB "[\| " \-c " \|]"
.RB "[\| " \-l
.IR language " \|]"
.RB "[\| " \-s
.IR separator " \|]"
.I selector
.SH DESCRIPTION
.B hxselect
reads a well-formed XML document and outputs elements that match the
CSS selector that is given as an argument. For example
.d
.B hxselect ol li:first-child
.e
selects the first li (list item in XHTML) in an ol (ordered list).
.PP
The command operates on the standard input.
.PP
Assumes that class selectors (".foo") refer to an attribute called
"class".
.PP
Assumes that ID selectors ("#foo") refer to an attribute called "id".
.SH OPTIONS
The following options are supported:
.TP 10
.B \-i
Match case-insensitively. Useful for HTML and some other
SGML-based languages.
.TP
.B \-c
Print content only. Without \fB\-c\fR, the start and end tag of the
matched element are printed as well; with \fB\-c\fR only the contents
of the matched element are printed.
.TP
.BI \-l " language"
Sets the default language, in case the root element doesn't
have an xml:lang attribute (default: none). Example:
.B \-l en
.TP
.BI \-s " separator"
A string to print after each match (default: empty). Accepts
C-like escapes. Example: 
.B \-s \(aq\\\\n\\\\n\(aq
to print an empty line after each match.
.TP
.B \-?
Show command usage.
.SH OPERANDS
The following operand is supported:
.TP
.I selector
A selector. Most selectors from CSS level 3 are supported, with the
exception of pseudo-classes, pseudo-elements and selectors with
\fBlast\-\fR in their name.
